[command]
default=echo "[INFO] Extracting UM and related repositories"

[file:$SOURCE_DIRECTORY/casim]
source=git:https://github.com/MetOffice/casim.git::./::um13.1

[file:$SOURCE_DIRECTORY/shumlib]
source=git:https://github.com/MetOffice/shumlib.git::./::um13.1

[file:$SOURCE_DIRECTORY/socrates]
source=git:https://github.com/MetOffice/socrates.git::./::um13.1

[file:$SOURCE_DIRECTORY/ukca]
source=git:https://github.com/MetOffice/ukca.git::./::um13.1

[file:$SOURCE_DIRECTORY/um]
# UM repository is private - Use local mirror
source=git:$GIT_MIRROR_LOC/um.git::./::vn13.1

[file:$SOURCE_DIRECTORY/jules]
# Jules-internal repsitory is private - use local mirror
source=git:$GIT_MIRROR_LOC/jules-internal.git::./::um13.1